# Generated by Django 5.0.2 on 2024-09-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add2cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.IntegerField()),
                ('fullname', models.CharField(max_length=20)),
                ('card', models.CharField(max_length=20)),
                ('cardno', models.CharField(max_length=12)),
                ('proname', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='media/')),
                ('price', models.CharField(max_length=20)),
                ('stock', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardno', models.CharField(max_length=12)),
                ('fullname', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('cardno', models.CharField(max_length=12)),
                ('card', models.CharField(max_length=12)),
                ('proname', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('license', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('apl', models.CharField(max_length=20)),
                ('bpl', models.CharField(max_length=20)),
                ('ay', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('stock', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('cardno', models.CharField(max_length=12)),
                ('card', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('locality', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='sreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('license', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='super_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
