# Generated by Django 5.0.2 on 2024-09-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add2cart',
        ),
    ]
