# Generated by Django 5.0.2 on 2024-09-27 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_app', '0002_delete_add2cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='add2cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ration_app.pro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ration_app.reg')),
            ],
        ),
    ]
